import type { ReactNode } from 'react'
import { ArrowLeft, ChevronRight, Heart, MapPin, Star } from 'lucide-react'
import { motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'

export function Chip({ children, active = false }: { children: ReactNode; active?: boolean }) { return <span className={`chip ${active ? 'chip-active' : ''}`}>{children}</span> }
export function BackHeader({ title, right }: { title?: string; right?: ReactNode }) { const navigate = useNavigate(); return <header className="back-header"><button className="icon-button" onClick={() => navigate(-1)} aria-label="뒤로 가기"><ArrowLeft size={19} /></button><strong>{title}</strong><span>{right}</span></header> }
export function PageMotion({ children, className = '' }: { children: ReactNode; className?: string }) { return <motion.section className={className} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.28 }}>{children}</motion.section> }
export function RegionCard({ region, city, score, image, onClick }: { region: string; city: string; score: string; image: string; onClick?: () => void }) { return <motion.article className="region-card" whileHover={{ y: -2 }} whileTap={{ scale: 0.99 }} onClick={onClick} role={onClick ? 'button' : undefined} tabIndex={onClick ? 0 : undefined}><img src={image} alt={`${region} ${city}`} /><div className="region-shade" /><span className="score">추천도 {score}</span><div className="region-title"><span>{region}</span><b>{city}</b></div><div className="region-tags"><Chip>바다</Chip><Chip>카페거리</Chip><Chip>워케이션</Chip><Chip>자연</Chip></div><div className="region-summary"><div><small>체류 추천 기간</small><strong>2~4주</strong></div><span className="chevron-circle"><ChevronRight size={17} /></span></div></motion.article> }
export function StayCard({ name, price, rating, image, tags, compact = false }: { name: string; price: string; rating: string; image: string; tags: string[]; compact?: boolean }) { return <motion.article className={`stay-card ${compact ? 'stay-compact' : ''}`} whileHover={{ y: -2 }}><div className="stay-image"><img src={image} alt={name} /><button className="like-button" aria-label={`${name} 찜하기`}><Heart size={15} /></button></div><div className="stay-info"><div className="stay-heading"><div><h3>{name}</h3><strong>{price}</strong></div><span className="rating"><Star size={12} fill="currentColor" /> {rating}</span></div><div className="chips">{tags.map((tag) => <Chip key={tag}>{tag}</Chip>)}</div></div></motion.article> }
export function StatCard({ label, value }: { label: string; value: string }) { return <article className="stat-card"><small>{label}</small><strong>{value}</strong></article> }
export function PlaceRow({ number, name, image }: { number: number; name: string; image: string }) { return <div className="place-row"><span className="place-number">{number}</span><p>{name}</p><img src={image} alt="" /></div> }
export function LocationLine({ children }: { children: ReactNode }) { return <span className="location-line"><MapPin size={14} fill="currentColor" />{children}</span> }